### ISSUE TITLE
Change start view or tab bar order

### ISSUE THREAD

**Issue by arpi09** [careerfairsystems/arkad-app#313]
As it is now the landing screen is the tab "map" and the tab which is in the middle is the tab "companies". It is kinda strange that the most important tab is not the landing screen. Either set the map in the middle or the screen "companies" as starting screen. As it is now, it looks like we can't decide on which of the screens that are most important.

**Comment by Alexander-Mjoberg** [comment]
This is my fault! 
We know from a survey that companies is the most important screen, and that map/profile is the second most, so according to our UX coordinator companies should be in the middle and be the start screen. However the API loading seems to be linked to map - if you dont go to map then companies don't load. So ideally we should make companies the initialRoute and have it load companies, otherwise change it to order map - events - companies - profile - about
